### ISSUE TITLE
Injector stolen from fate client 🥱 

### ISSUE THREAD

**Issue by FloppyDolphin57** [TeknoCOM/HorionClient#1]

**Comment by matt-36** [comment]
troo aha

**Comment by fligger** [comment]
https://github.com/fligger/FateInjector/blob/master/LICENSE

You know I have a licence for you to follow. What you are doing is just really sad.

**Comment by belohnung** [comment]
;( bruh momento

**Comment by WinkeyCheng** [comment]
I'm so sorry, but I don't have anytime to build a new injector lol

**Comment by matt-36** [comment]
Bruh creating an injector isn't very hard lol
